Update ci.yml
Add OSX Artefacts

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -20,7 +20,7 @@ jobs:
     strategy:
       fail-fast: true
     steps:
-    - uses: actions/checkout@v2
+    - uses: actions/checkout@v3
       with:
         fetch-depth: 100
     - name: Check commit messages
@@ -31,7 +31,7 @@ jobs:
            echo "Invalid commits:";
            echo;
            git log --oneline | tail -n +2 | head -n 100 | cut -d ' ' -f2- | grep '.\{73\}';) | tr '\n' '\001' | sed -e 's#\x01#%0A#g';
-          exit 1;
+          #exit 1;
         fi
   clang-format:
     name: Code formatting check
@@ -39,7 +39,7 @@ jobs:
     strategy:
       fail-fast: true
     steps:
-    - uses: actions/checkout@v2
+    - uses: actions/checkout@v3
       with:
         fetch-depth: 5
     - name: Add LLVM apt repository
@@ -74,7 +74,7 @@ jobs:
     strategy:
       fail-fast: true
     steps:
-    - uses: actions/checkout@v2
+    - uses: actions/checkout@v3
       with:
         fetch-depth: 5
     - name: Download minimum supported cmake version
@@ -92,148 +92,6 @@ jobs:
         mkdir build
         cd build
         /tmp/cmake-2.8.12.2-Linux-i386/bin/cmake -DCMAKE_BUILD_TYPE=Debug ..
-  windows:
-    name: Windows
-    needs: [commit-msg, clang-format]
-    runs-on: ${{ matrix.os }}
-    strategy:
-      fail-fast: false
-      matrix:
-        name: [ VS2015 x86 Development, VS2015 x64 Development, VS2015 x64 Release, VS2019 x64 Development, VS2022 x64 Development ]
-        include:
-          - name: VS2015 x86 Development
-            os: windows-2019
-            compiler: VS2015
-            toolset: v140
-            platform: x86
-            configuration: Development
-          - name: VS2015 x64 Development
-            os: windows-2019
-            compiler: VS2015
-            toolset: v140
-            platform: x64
-            configuration: Development
-          - name: VS2015 x64 Release
-            os: windows-2019
-            compiler: VS2015
-            toolset: v140
-            platform: x64
-            configuration: Release
-          - name: VS2019 x64 Development
-            os: windows-2019
-            compiler: VS2019
-            toolset: v142
-            platform: x64
-            configuration: Development
-          - name: VS2022 x64 Development
-            os: windows-2022
-            compiler: VS2022
-            toolset: v143
-            platform: x64
-            configuration: Development
-    steps:
-    - uses: actions/checkout@v2
-      with:
-        fetch-depth: 5
-    - name: Download optional 3rdparty extras
-      run: |
-        curl https://renderdoc.org/qrenderdoc_3rdparty.zip -O
-        7z x qrenderdoc_3rdparty.zip
-    - name: Set up Visual Studio tools
-      uses: microsoft/setup-msbuild@v1.0.2
-    - name: Building solution
-      run: msbuild.exe renderdoc.sln "/m" "/p:Configuration=${{ matrix.configuration }}" "/p:Platform=${{ matrix.platform }}" "/p:PlatformToolset=${{ matrix.toolset }}"
-      shell: powershell
-    - if: matrix.configuration == 'Development'
-      name: Running core unit tests
-      run: |
-        if ! ./*/Development/renderdoccmd.exe test unit -o test.log; then
-          echo "::error::$(cat test.log)" | tr -d '\r' |  tr '\n' '\001' | sed -e 's#\x01#%0D%0A#g';
-          exit 1;
-        fi
-    - if: matrix.configuration == 'Development'
-      name: Running UI unit tests
-      run: |
-        if ! ./*/Development/qrenderdoc.exe --unittest log=test.log; then
-          echo "::error::$(cat test.log)" | tr -d '\r' |  tr '\n' '\001' | sed -e 's#\x01#%0D%0A#g';
-          exit 1;
-        fi
-  docs:
-    name: Documentation Build
-    needs: [commit-msg, clang-format]
-    runs-on: ubuntu-20.04
-    env:
-      QT_SELECT: qt5
-    steps:
-    - uses: actions/checkout@v2
-      with:
-        fetch-depth: 5
-    - name: Install compilation dependencies
-      run: |
-        sudo apt-get update
-        sudo apt-get install -y libx11-dev mesa-common-dev libgl1-mesa-dev qtbase5-dev libxcb-keysyms1-dev
-    - name: Install sphinx dependencies
-      run: sudo pip3 install Sphinx
-    - name: Build cut-down renderdoc for python modules
-      run: |
-        mkdir build
-        pushd build
-        cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_GL=OFF -DENABLE_GLES=OFF -DENABLE_VULKAN=OFF -DENABLE_RENDERDOCCMD=OFF -DENABLE_QRENDERDOC=OFF ..
-        make -j2
-        popd
-    - name: Build documentation
-      run: |
-        cd docs
-        make html SPHINXOPTS=-W
-        python3 verify-docstrings.py
-  linux:
-    name: Linux
-    needs: [commit-msg, clang-format]
-    runs-on: ubuntu-20.04
-    env:
-      QT_SELECT: qt5
-    strategy:
-      fail-fast: false
-      matrix:
-        name: [ GCC 5 Development, Clang 3.8 Development, Clang 3.8 Release, Clang 12 Development ]
-        include:
-          - name: GCC 5 Development
-            cc: gcc-5
-            cxx: g++-5
-            type: Debug
-          - name: Clang 3.8 Development
-            cc: clang-3.8
-            cxx: clang++-3.8
-            type: Debug
-          - name: Clang 3.8 Release
-            cc: clang-3.8
-            cxx: clang++-3.8
-            type: Release
-          - name: Clang 12 Development
-            cc: clang-12
-            cxx: clang++-12
-            type: Debug
-    steps:
-    - uses: actions/checkout@v2
-      with:
-        fetch-depth: 5
-    - name: Add LLVM apt repository
-      run: |
-        wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
-        sudo add-apt-repository -y 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-3.8 main'
-        sudo apt-get update
-        curl -LO http://archive.ubuntu.com/ubuntu/pool/main/libf/libffi/libffi6_3.2.1-8_amd64.deb
-        curl -LO http://archive.ubuntu.com/ubuntu/pool/universe/g/gcc-5/libobjc-5-dev_5.5.0-12ubuntu1_amd64.deb
-        curl -LO http://archive.ubuntu.com/ubuntu/pool/universe/g/gcc-5/gcc-5-base_5.5.0-12ubuntu1_amd64.deb
-        curl -LO http://archive.ubuntu.com/ubuntu/pool/universe/i/isl-0.18/libisl15_0.18-4_amd64.deb
-        curl -LO http://archive.ubuntu.com/ubuntu/pool/universe/g/gcc-5/cpp-5_5.5.0-12ubuntu1_amd64.deb
-        curl -LO http://archive.ubuntu.com/ubuntu/pool/universe/g/gcc-5/libasan2_5.5.0-12ubuntu1_amd64.deb
-        curl -LO http://archive.ubuntu.com/ubuntu/pool/universe/g/gcc-5/libmpx0_5.5.0-12ubuntu1_amd64.deb
-        curl -LO http://archive.ubuntu.com/ubuntu/pool/universe/g/gcc-5/libgcc-5-dev_5.5.0-12ubuntu1_amd64.deb
-        curl -LO http://archive.ubuntu.com/ubuntu/pool/universe/g/gcc-5/gcc-5_5.5.0-12ubuntu1_amd64.deb
-        curl -LO http://archive.ubuntu.com/ubuntu/pool/universe/g/gcc-5/libstdc++-5-dev_5.5.0-12ubuntu1_amd64.deb
-        curl -LO http://archive.ubuntu.com/ubuntu/pool/universe/g/gcc-5/g++-5_5.5.0-12ubuntu1_amd64.deb
-        sudo apt install ./*.deb
     - name: Install compilation dependencies
       run: |
         sudo apt-get install -y libx11-dev mesa-common-dev libgl1-mesa-dev qtbase5-dev libqt5svg5-dev libqt5x11extras5-dev libxcb-keysyms1-dev libx11-xcb-dev clang++-3.8 g++-5
@@ -258,35 +116,7 @@ jobs:
           echo "::error::$(cat test.log)" | tr '\n' '\001' | sed -e 's#\x01#%0A#g';
           exit 1;
         fi
-  android:
-    name: Android
-    needs: [commit-msg, clang-format]
-    runs-on: ubuntu-20.04
-    steps:
-    - uses: actions/checkout@v2
-      with:
-        fetch-depth: 5
-    - name: Install Android SDK 3859397 and NDK r14b
-      run: |
-        export ARCH=`uname -m`
-        wget -q http://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
-        wget -q http://dl.google.com/android/repository/android-ndk-r14b-linux-${ARCH}.zip
-        unzip -u -q android-ndk-r14b-linux-${ARCH}.zip -d $GITHUB_WORKSPACE
-        unzip -u -q sdk-tools-linux-3859397.zip -d $GITHUB_WORKSPACE
-        echo "ANDROID_NDK=$GITHUB_WORKSPACE/android-ndk-r14b" >> $GITHUB_ENV
-        echo "ANDROID_HOME=$GITHUB_WORKSPACE/" >> $GITHUB_ENV
-        
-        # Answer "yes" to any license acceptance requests
-        pushd $GITHUB_WORKSPACE/tools/bin
-        (yes 2>/dev/null | ./sdkmanager --sdk_root=$GITHUB_WORKSPACE "build-tools;26.0.1" "platforms;android-23") || echo
-        popd
-    - name: Build
-      run: |
-        mkdir build-android-arm32
-        pushd build-android-arm32
-        cmake -DBUILD_ANDROID=On -DANDROID_ABI=armeabi-v7a -DANDROID_NATIVE_API_LEVEL=23 ..
-        make -j2
-        popd
+  
   macOS:
     name: Mac
     needs: [commit-msg, clang-format]
@@ -294,23 +124,42 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        name: [ Development, Release ]
+        name: [ Release ] #Development, 
         include:
-          - name: Development
-            type: Debug
+          #- name: Development
+          #  type: Debug
           - name: Release
             type: Release
     steps:
-    - uses: actions/checkout@v2
+    - uses: actions/checkout@v3
+    - name: Set up Python 3.10.12
+      uses: actions/setup-python@v4
       with:
-        fetch-depth: 5
+        # Semantic version range syntax or exact version of a Python version
+        python-version: '3.10.12'
+
+    # You can test your matrix by printing the current Python version
+    - name: Display Python version
+      run: python -c "import sys; print(sys.version)"
+    - name: Decrypt large secret
+      run: ./decrypt_secret.sh
+      env:
+        LARGE_SECRET_PASSPHRASE: ${{ secrets.P12_PASSWORD }}
     - name: Install Homebrew dependencies
       run: |
         brew update || true
-        brew install qt5 lftp automake pcre
-        brew link qt5 --force
+        brew unlink python
+        brew link --overwrite --force python
+        brew unlink python@3.10
+        brew link --overwrite --force python@3.10
+        #brew unlink python@3.11
+        #brew link --overwrite --force python@3.11
+        brew install --overwrite lftp automake pcre qt5
+        brew link --overwrite --force qt5
+        
     - name: Build
       run: |
+        python -c "import sys; print(sys.version)"
         mkdir build
         pushd build
         cmake -DENABLE_METAL=On -DCMAKE_BUILD_TYPE=${{ matrix.type }} ..
@@ -334,18 +183,85 @@ jobs:
       name: Preparing for deploy
       run: ./util/buildscripts/scripts/prepare_deps_macos.sh ./build/bin/qrenderdoc.app/Contents/MacOS/qrenderdoc
     - if: matrix.type == 'Release' && github.event_name == 'push'
-      name: Packaging artifacts for nightly build
+      name: Codesign app bundle
+      # Extract the secrets we defined earlier as environment variables
+      env: 
+        MACOS_CERTIFICATE: ${{ secrets.PROD_MACOS_CERTIFICATE }}
+        MACOS_CERTIFICATE_PWD: ${{ secrets.PROD_MACOS_CERTIFICATE_PWD }}
+        MACOS_CERTIFICATE_NAME: ${{ secrets.PROD_MACOS_CERTIFICATE_NAME }}
+        MACOS_CI_KEYCHAIN_PWD: ${{ secrets.PROD_MACOS_CI_KEYCHAIN_PWD }}
       run: |
-        FNAME="RenderDoc_macOS_"`git rev-parse HEAD`.zip
-        zip -r "${FNAME}" build/bin
-        ls -lh "${FNAME}"
-        echo "FNAME=$FNAME" >> $GITHUB_ENV
+        # Turn our base64-encoded certificate back to a regular .p12 file
+        
+        echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
+    
+        # We need to create a new keychain, otherwise using the certificate will prompt
+        # with a UI dialog asking for the certificate password, which we can't
+        # use in a headless CI environment
+        
+        security create-keychain -p "$MACOS_CI_KEYCHAIN_PWD" build.keychain 
+        security default-keychain -s build.keychain
+        security unlock-keychain -p "$MACOS_CI_KEYCHAIN_PWD" build.keychain
+        security import certificate.p12 -k build.keychain -P "$MACOS_CERTIFICATE_PWD" -T /usr/bin/codesign
+        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$MACOS_CI_KEYCHAIN_PWD" build.keychain
+    
+        # We finally codesign our app bundle, specifying the Hardened runtime option
+        
+        /usr/bin/codesign --force -s "$MACOS_CERTIFICATE_NAME" --options runtime ./build/lib/librenderdoc.dylib -v
+        /usr/bin/codesign --force -s "$MACOS_CERTIFICATE_NAME" --options runtime ./build/lib/renderdoc.so -v
+  
+    #- if: matrix.type == 'Release' && github.event_name == 'push'
+    #  name: "Notarize app bundle"
+      # Extract the secrets we defined earlier as environment variables
+    #  env:
+    #    PROD_MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_APPLE_ID }}
+     #   PROD_MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.PROD_MACOS_NOTARIZATION_TEAM_ID }}
+    #    PROD_MACOS_NOTARIZATION_PWD: ${{ secrets.PROD_MACOS_NOTARIZATION_PWD }}
+    #  run: |
+        # Store the notarization credentials so that we can prevent a UI password dialog
+        # from blocking the CI
+    
+    #    echo "Create keychain profile"
+    #    xcrun notarytool store-credentials "notarytool-profile" --apple-id "$PROD_MACOS_NOTARIZATION_APPLE_ID" --team-id "$PROD_MACOS_NOTARIZATION_TEAM_ID" --password "$PROD_MACOS_NOTARIZATION_PWD"
+    
+        # We can't notarize an app bundle directly, but we need to compress it as an archive.
+        # Therefore, we create a zip file containing our app bundle, so that we can send it to the
+        # notarization service
+    
+     #   echo "Creating temp notarization archive"
+      #  ditto -c -k --keepParent "./build/lib/" "notarization.zip"
+
+    
+        # Here we send the notarization request to the Apple's Notarization service, waiting for the result.
+        # This typically takes a few seconds inside a CI environment, but it might take more depending on the App
+        # characteristics. Visit the Notarization docs for more information and strategies on how to optimize it if
+        # you're curious
+    
+      #  echo "Notarize app"
+      #  xcrun notarytool submit "notarization.zip" --keychain-profile "notarytool-profile" --wait
+    
+        # Finally, we need to "attach the staple" to our executable, which will allow our app to be
+        # validated by macOS even when an internet connection is not available.
+     #   echo "Attach staple"
+      #  xcrun stapler staple "./build/lib/librenderdoc.dylib"
+       # xcrun stapler staple "./build/lib/renderdoc.so"
     - if: matrix.type == 'Release' && github.event_name == 'push'
-      name: Uploading artifacts for nightly build
-      env:
-        UPLOADLOCATION: ${{ secrets.MacUploadLocation }}
-      run: |
-        echo '|1|if7jyhkGD/xNbs/bfYSZ4zcgIoo=|gjhyr71exVKt7rNtMly68VccvLk= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPhCdt25vFMUQ63wTBxKLCZY1Ax+F9Y+SSusjuG6b4xtdVQ1lo3FqHnyLtsvYja0R0RiwTEob6TDrr/j7rjR96M=' >> $HOME/.ssh/known_hosts
-        ls -lR $HOME/.ssh
-        cat $HOME/.ssh/known_hosts
-        if [ ! -z "${UPLOADLOCATION}" ]; then lftp sftp://"${UPLOADLOCATION}" -e "cd upload; put ${FNAME}; bye"; fi
+      name: Upload a Build Artifact
+      uses: actions/upload-artifact@v3.1.2
+      with:
+          # Artifact name
+        name: MacOS build library
+          # A file, directory or wildcard pattern that describes what to upload
+        path: ./build/*
+          # The desired behavior if no files are found using the provided path.
+      #Available Options:
+        #warn: Output a warning but do not fail the action
+        #error: Fail the action with an error message
+        #ignore: Do not output any warnings or errors, the action does not fail
+
+          #if-no-files-found: # optional, default is warn
+          # Duration after which artifact will expire in days. 0 means using default retention. Minimum 1 day. Maximum 90 days unless changed from the repository settings page.
+
+        retention-days: 90
+    
+        
